name: $[format('1.0.{0}', counter('1.0', 0))]

trigger:
  branches:
    include:
    - main

jobs:
- job: build
  displayName: Build, Run Tests and Publish Artifacts Job
  pool:
    vmImage: windows-latest

  steps:

  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    displayName: Use NuGet
    inputs:
      versionSpec: 6.1.0

  - task: DotNetCoreCLI@2
    displayName: Restore NuGet Packages
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build Projects
    inputs:
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: test
      projects: '**/$(ProjectPath).*Test*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Publish Nuget Packages
    inputs:
      command: 'pack'
      packagesToPack: '**\*.csproj;!**/*Test*.csproj;!'
      packDirectory: '$(Build.ArtifactStagingDirectory)/NuGetPackages'
      versioningScheme: 'byBuildNumber'

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact NuGet Packages
    
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/NuGetPackages'
      artifact: 'NuGetPackages'
      publishLocation: 'pipeline'
...